# Generated by Django 4.1.5 on 2023-02-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_firstname_customuser_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
