# Generated by Django 4.1.5 on 2023-02-02 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickness', models.CharField(max_length=200, verbose_name='Sickness')),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Check-in Date')),
                ('meds', models.TextField(verbose_name='Medication')),
                ('meds_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Set Medication Alert Time')),
            ],
        ),
    ]
