# Generated by Django 4.1.5 on 2023-02-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickness', models.CharField(max_length=200)),
                ('meds', models.CharField(max_length=200)),
                ('orderloan', models.IntegerField()),
            ],
        ),
    ]
