# Generated by Django 4.1.5 on 2023-01-28 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_remove_medicine_checkin_remove_orderloan_checkin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickness', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('meds', models.CharField(blank=True, default='None', max_length=200, null=True)),
                ('complete_meds', models.BooleanField()),
                ('orderloan', models.IntegerField(default=0)),
                ('complete_loan', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
