# Generated by Django 4.1.5 on 2023-01-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='complete_loan',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='complete_meds',
        ),
    ]
